/**
 * UI strings. Arabic is the source dictionary; English is a partial overlay that
 * falls back to Arabic for any missing key, so the UI is never broken — only
 * partially translated. Call sites use `S.x` unchanged; `S` reads the active
 * locale (see config/locale.ts) at access time.
 */
import { getLocale } from './locale';

const ar = {
  appName: 'Bt Lee',

  // Currency / units (from property.* keys)
  currency: 'ج.م',
  perMonth: '/ شهرياً',
  priceOnRequest: 'السعر عند التواصل',
  areaUnit: 'م²',
  in: 'في',

  // Common
  back: 'رجوع',

  // Card badges
  featured: 'مميز',
  new: 'جديد',

  // Tabs
  tabHome: 'الرئيسية',
  tabProperties: 'العقارات',
  tabWishlist: 'المفضلة',
  tabProfile: 'حسابي',

  // Home
  heroTitle: 'اعلن عقارك من غير عمولة',
  heroTitleLead: 'اعلن عقارك',
  heroTitleEmphasis: "من غير عمولة وفر بسهولة",
  heroTitleAccent: 'بيع واشترى من غير سمسار',
  heroSubtitle: 'آلاف العقارات للبيع والإيجار في كل محافظات مصر',
  trustVerified: 'إعلانات موثقة',
  trustDirect: 'تواصل مباشر',
  trustNoCommission: 'بدو ن عمولات',
  searchPillTitle: 'دوّر على عقـارك',
  searchPillHint: 'مدينة، منطقة، أو نوع عقار',
  searchExamplePrefix: 'جرّب: ',
  searchExamples: ['شقة في المعادي', 'فيلا في الشيخ زايد', 'محل في مدينة نصر', 'شاليه في الساحل', 'دوبلكس في التجمّع'],
  introTagline: 'عقارات من غير عمولة',
  sortLabel: 'ترتيب',
  bannerCta: 'أضف إعلانك مجاناً',
  bannerEyebrow: 'لأصحاب العقارات',
  roomsShort: 'غرف',
  bathsShort: 'حمام',
  available: 'متوفر',
  contactWhatsApp: 'تواصل واتساب',
  toastWishlistAdded: 'اتضاف للمفضلة',
  toastWishlistRemoved: 'اتشال من المفضلة',
  startSearch: 'ابدأ البحث',
  exploreByType: 'استكشـف حـسـب النـوع',
  featuredTitle: 'عقــارات مميــزة',
  latestTitle: 'أحــدث العقـارات',
  rentSectionTitle: 'عقــارات للإيجــار',
  saleSectionTitle: 'عقــارات للبـيـع',
  citySectionTitle: 'عقــارات في القاهــرة',
  viewAll: 'عرض الكل',
  addListingSub: 'انشر عقارك في دقائق',
  browseProps: 'تصفّح العقارات',
  browsePropsSub: 'آلاف العقارات',
  listYourProperty: 'عندك عقار للبيع أو الإيجار؟',
  listYourPropertySub: 'انشره مجاناً ووصّل لآلاف المهتمين',

  // Properties list
  searchPlaceholder: 'ابحث عن مدينة، منطقة، أو نوع عقار...',
  resultsCount: (n: number) => `${n} نتيجة`,
  searchNoMatches: 'لا نتائج مطابقة',
  searchAndFilter: 'بحث وتصفية',
  showResults: 'عرض النتائج',
  searchHint: 'ابحث وفلتر النتائج',

  // Filters & sort
  filterBtn: 'تصفية',
  sortBtn: 'الترتيب',
  filterTitle: 'تصفية النتائج',
  sortTitle: 'الترتيب',
  apply: 'تطبيق',
  reset: 'إعادة تعيين',
  clearAll: 'مسح الكل',
  all: 'الكل',
  fListingType: 'نوع الصفقة',
  fType: 'نوع العقار',
  fCategory: 'التصنيف',
  fGovernorate: 'المحافظة',
  govPickerPlaceholder: 'اختر المحافظة',
  govPickerTitle: 'اختر المحافظة',
  govPickerSearch: 'ابحث عن محافظة...',
  govPickerEmpty: 'لا توجد محافظة بهذا الاسم',
  pricePickerTitle: 'اختر السعر',
  pricePickerPlaceholder: 'اختر السعر',
  areaPickerTitle: 'اختر المساحة',
  areaPickerPlaceholder: 'اختر المساحة',
  amountPickerCustom: 'أو اكتب قيمة...',
  amountPickerNone: 'بدون تحديد',
  countPickerPlaceholder: 'اختر العدد',
  yearPickerTitle: 'اختر سنة الصنع',
  yearPickerPlaceholder: 'اختر السنة',
  mileagePickerTitle: 'اختر الكيلومترات',
  mileagePickerPlaceholder: 'اختر الكيلومترات',
  fPrice: 'السعر (ج.م)',
  fMinPrice: 'من',
  fMaxPrice: 'إلى',
  fMinBedrooms: 'غرف النوم (على الأقل)',
  fMinArea: 'المساحة على الأقل (م²)',
  fFinishing: 'حالة التشطيب',
  chipMinPrice: (n: string) => `السعر من: ${n}`,
  chipMaxPrice: (n: string) => `السعر إلى: ${n}`,
  chipMinBedrooms: (n: number) => `غرف: ${n}+`,
  chipMinArea: (n: number) => `مساحة: ${n}+ م²`,
  loading: 'جارٍ التحميل',
  noResultsTitle: 'لا نتائج',
  noResultsDesc: 'جرّب تعديل كلمة البحث',
  errorTitle: 'حصل خطأ',
  errorDesc: 'تعذّر تحميل العقارات، حاول تاني',
  retry: 'إعادة المحاولة',

  // Detail
  contactOwner: 'تواصل مع صاحب العقار',
  viewOnMap: 'عرض على الخريطة',
  descriptionLabel: 'الوصف',
  detailsLabel: 'التفاصيل',
  bedrooms: 'غرف نوم',
  bathrooms: 'حمامات',
  floor: 'الدور',
  area: 'المساحة',
  finishingLabel: 'التشطيب',
  elevator: 'أسانسير',
  garage: 'جراج',
  servicesLabel: 'الخدمات المتوفرة',
  depositLabel: 'التأمين المطلوب',
  listingNumber: 'رقم الإعلان',
  views: 'مشاهدة',

  // Auth
  signInTitle: 'تسجيل الدخول',
  signInSubtitle: 'أهلاً بعودتك إلى بيت لي',
  registerTitle: 'إنشاء حساب جديد',
  registerSubtitle: 'انضم إلى بيت لي وابدأ رحلتك العقارية',
  nameLabel: 'الاسم',
  emailOrPhoneLabel: 'البريد الإلكتروني أو رقم الهاتف',
  emailLabel: 'البريد الإلكتروني',
  phoneLabel: 'رقم الهاتف',
  passwordLabel: 'كلمة المرور',
  signInBtn: 'دخول',
  createAccountBtn: 'إنشاء حساب',
  noAccount: 'ليس لديك حساب؟',
  hasAccount: 'لديك حساب؟',
  logout: 'تسجيل الخروج',
  deleteAccount: 'حذف الحساب',
  deleteAccountConfirm:
    'سيتم حذف حسابك وكل بياناتك وإعلاناتك نهائياً، ولا يمكن التراجع عن ذلك. هل أنت متأكد أنك تريد المتابعة؟',
  deleteAccountCta: 'حذف الحساب نهائياً',
  // Validation
  required: 'هذا الحقل مطلوب',
  invalidEmail: 'البريد الإلكتروني غير صحيح',
  invalidPhone: 'أدخل رقم هاتف مصري صحيح (مثال: 01012345678)',
  passwordMin: 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
  loginFailed: 'بيانات الدخول غير صحيحة',
  or: 'أو',
  googleSignIn: 'المتابعة بحساب جوجل',
  googleSignInFailed: 'تعذّر تسجيل الدخول عبر جوجل',
  agreePrefix: 'أوافق على ',
  termsLink: 'الشروط والأحكام',
  andWord: 'و',
  mustAcceptTerms: 'لازم توافق على الشروط والأحكام الأول',

  // Add / edit property
  addPropertyTitle: 'أضف إعلانك',
  editPropertyTitle: 'تعديل الإعلان',
  fImages: 'صور العقار',
  addImages: 'أضف صور',
  fBedrooms: 'غرف النوم',
  fBathrooms: 'الحمامات',
  fFloor: 'الدور',
  fAreaM: 'المساحة (م²)',
  fPriceOne: 'السعر (ج.م)',
  fServices: 'الخدمات المتوفرة',
  fElevator: 'أسانسير',
  fGarage: 'جراج',
  fDeposit: 'التأمين المطلوب',
  fAreaName: 'المنطقة / الحي',
  fDescription: 'وصف العقار',
  fWhatsapp: 'رقم واتساب للتواصل',
  fDuration: 'مدة عرض الإعلان',
  days: 'يوم',
  optional: '(اختياري)',
  submitAdd: 'نشر الإعلان',
  submitEdit: 'حفظ التعديلات',
  uploadingImages: 'جاري رفع الصور...',
  publishing: 'جاري النشر...',
  addSuccessTitle: 'تم إرسال إعلانك',
  addSuccessDesc: 'هيظهر بعد مراجعة الفريق',
  fillRequired: 'اكمل الحقول المطلوبة',
  imagesRequired: 'أضف صورة واحدة على الأقل',
  whatsappHint: 'مثال: 01012345678',
  descriptionHint: 'اكتب تفاصيل العقار (10 أحرف على الأقل)',
  phMake: 'مثال: تويوتا',
  phModel: 'مثال: كورولا',
  phColor: 'مثال: أسود',
  phAreaName: 'مثال: المعادي، مدينة نصر',
  phFloor: 'مثال: 3',
  phDescription: 'اكتب تفاصيل واضحة تجذب المهتمين...',
  fLocation: 'موقع العقار على الخريطة',
  tapToSetLocation: 'دوس على الخريطة لتحديد موقع العقار',
  locationSelected: 'تم تحديد الموقع',

  // My properties
  myPropertiesTitle: 'إعلاناتي',
  addNew: 'أضف إعلان',
  noListingsTitle: 'مفيش إعلانات',
  noListingsDesc: 'ابدأ بإضافة أول إعلان ليك',
  editListing: 'تعديل',
  deleteListing: 'حذف',
  markSold: 'تم البيع',
  markRented: 'تم التأجير',
  confirmDeleteTitle: 'حذف الإعلان؟',
  confirmDeleteDesc: 'مش هتقدر ترجعه تاني',
  cancel: 'إلغاء',
  rejectionReason: 'سبب الرفض',
  viewsCount: (n: number) => `${n} مشاهدة`,

  // Notifications
  notificationsTitle: 'الإشعارات',
  notificationsEmpty: 'مفيش إشعارات',
  markAllRead: 'قراءة الكل',

  // Ratings
  ratingsTitle: 'التقييم',
  ratingsCount: (n: number) => `${n} تقييم`,
  noRatings: 'لا توجد تقييمات بعد',
  rateThis: 'قيّم هذا العقار',
  rateThisCar: 'قيّم هذه العربية',
  yourRating: 'تقييمك',
  loginToRate: 'سجّل دخولك أولاً لتقييم العقار',
  loginToRateCar: 'سجّل دخولك أولاً لتقييم العربية',

  // Report
  reportListing: 'الإبلاغ عن الإعلان',
  reportTitle: 'الإبلاغ عن هذا الإعلان',
  reportDetailsPlaceholder: 'تفاصيل إضافية (اختياري)',
  reportChooseReason: 'اختر سبب الإبلاغ',
  reportSubmit: 'إرسال البلاغ',
  reportSuccess: 'تم إرسال البلاغ، شكراً لك',

  // Similar + location
  similarProperties: 'عقارات مشابهة',
  locationLabel: 'الموقع',

  // Owner profile
  ownerProfile: 'صفحة المعلن',
  memberSince: 'عضو منذ',
  listingsCount: (n: number) => `${n} عقار منشور`,
  allListingsByOwner: 'كل إعلانات هذا المعلن',
  noOwnerListings: 'لا توجد إعلانات منشورة',

  // Saved searches
  savedSearchesTitle: 'عمليات البحث المحفوظة',
  savedSearchesEmpty: 'لا توجد عمليات بحث محفوظة',
  savedSearchesEmptyDesc: 'احفظ بحثك عشان يوصلك إشعار بأول عقار جديد يطابقه',
  saveSearch: 'حفظ البحث',
  savedSearchName: 'اسم البحث',
  savedSearchNamePlaceholder: 'مثال: شقق للإيجار في المعادي',
  savedSearchNameRequired: 'اكتب اسم للبحث',
  savedSearchSaved: 'تم حفظ البحث',
  savedSearchDeleteTitle: 'حذف البحث؟',
  applySearch: 'تطبيق البحث',

  // Account
  editProfileTitle: 'تعديل الملف الشخصي',
  changePasswordTitle: 'تغيير كلمة المرور',
  currentPasswordLabel: 'كلمة المرور الحالية',
  newPasswordLabel: 'كلمة المرور الجديدة',
  saveChanges: 'حفظ التغييرات',
  saveSuccess: 'تم حفظ التغييرات',
  nameInvalid: 'الاسم لازم يكون بين حرفين و60 حرف',
  passwordLetter: 'كلمة المرور لازم تحتوي على حرف واحد على الأقل',
  passwordDigit: 'كلمة المرور لازم تحتوي على رقم واحد على الأقل',
  currentPasswordWrong: 'كلمة المرور الحالية غير صحيحة',
  passwordChangedTitle: 'تم تغيير كلمة المرور',
  passwordChangedReLogin: 'سجّل دخولك من جديد بكلمة المرور الجديدة',

  // Forgot / reset password
  forgotPassword: 'نسيت كلمة المرور؟',
  resetPasswordTitle: 'إعادة تعيين كلمة المرور',
  resetPasswordDesc: 'أدخل بريدك الإلكتروني وهنبعتلك رابط إعادة التعيين',
  sendResetLink: 'إرسال الرابط',
  resetLinkSent: 'تم إرسال الرابط',
  resetLinkSentDesc: 'لو الإيميل ده مسجّل عندنا، هيوصلك رابط لإعادة التعيين',
  backToLogin: 'العودة لتسجيل الدخول',
  newPasswordTitle: 'تعيين كلمة مرور جديدة',
  newPasswordSubtitle: 'اختر كلمة مرور قوية لحسابك',
  confirmPasswordLabel: 'تأكيد كلمة المرور',
  setNewPassword: 'تعيين كلمة المرور',
  passwordNoMatch: 'كلمة المرور غير متطابقة',
  resetSuccess: 'تم تغيير كلمة المرور بنجاح، تقدر تسجّل دخولك دلوقتي',
  resetInvalidToken: 'رابط إعادة التعيين غير صالح أو منتهي الصلاحية',
  tooManyAttempts: 'تجاوزت عدد المحاولات المسموح بها. استنى 15 دقيقة وحاول تاني.',

  // Onboarding
  onboardingTitle: 'أهلاً بيك في Bt Lee',
  onboardingSubtitle: 'إيه اللي بتدوّر عليه؟',
  goalBuy: 'شراء عقار',
  goalRent: 'استئجار عقار',
  goalSell: 'بيع أو تأجير',
  goalBrowse: 'تصفّح فقط',
  skip: 'تخطّي',
  continue: 'متابعة',

  // Legal / about
  aboutApp: 'عن التطبيق',
  privacyTitle: 'سياسة الخصوصية',
  disclaimerTitle: 'إخلاء المسؤولية',
  dataDeletionTitle: 'حذف البيانات',

  // Language + appearance
  language: 'اللغة',
  appearance: 'المظهر',
  light: 'فاتح',
  dark: 'داكن',
  menuTitle: 'القائمة',
  viewProfile: 'عرض الملف الشخصي',
  contactUs: 'تواصل معنا',

  // Placeholders
  wishlistEmptyTitle: 'مفيش عقارات محفوظة',
  wishlistEmptyDesc: 'احفظ العقارات اللي عجباك وهتلاقيها هنا',
  wishlistEmptyTitleCar: 'مفيش عربيات محفوظة',
  wishlistEmptyDescCar: 'احفظ العربيات اللي عجباك وهتلاقيها هنا',
  profileGuestTitle: 'أهلاً بيك في Bt Lee',
  profileGuestDesc: 'سجّل دخولك عشان تحفظ عقارات وتضيف إعلانك',
  comingSoon: 'قريباً',
  loginToSave: 'سجل دخولك أولاً لحفظ العقارات',
  genericError: 'حدث خطأ، حاول مرة أخرى',

  // Section switcher
  sectionProperties: 'عقــارات',
  sectionCars: 'عربـيـات',

  // Cars — home
  carsHeroLead: 'اعلن عربيتك',
  carsHeroEmphasis: 'من غير عمولة وفر بسهولة',
  carsHeroSubtitle: 'آلاف العربيات للبيع والإيجار في كل محافظات مصر',
  carsSearchPillTitle: 'دوّر على عربيـتـك',
  carsSearchExamples: ['تويوتا كورولا', 'هيونداي إلنترا', 'كيا سبورتاج', 'مرسيدس C180', 'BMW 320i'],
  carsExploreByType: 'استكشـف حـسـب النـوع',
  carsFeaturedTitle: 'عربـيـات مميـزة',
  carsLatestTitle: 'أحــدث العربـيـات',
  carsSaleSectionTitle: 'عربيـات للبـيـع',
  carsRentSectionTitle: 'عربـيـات للإيجـار',

  // Cars — list + errors
  carsSearchPlaceholder: 'ابحث بالماركة أو الموديل...',
  carsResultsCount: (n: number) => `${n} عربية`,
  carsErrorDesc: 'تعذّر تحميل العربيات، حاول تاني',
  // Cars — filter sheet
  fMinYear: 'من سنة',
  fMaxYear: 'إلى سنة',
  fMaxMileage: 'أقصى كيلومترات',

  // Cars — spec labels
  kmUnit: 'كم',
  carYearLabel: 'سنة الصنع',
  carMileageLabel: 'الكيلومترات',
  carTransmissionLabel: 'ناقل الحركة',
  carFuelLabel: 'الوقود',
  carBodyTypeLabel: 'نوع الهيكل',
  carConditionLabel: 'الحالة',
  carColorLabel: 'اللون',
  carContactSeller: 'تواصل مع البائع',

  // Cars — add form
  addCarTitle: 'أضف عربيتك',
  addCarSuccessDesc: 'هتظهر بعد مراجعة الفريق',
  fCarImages: 'صور العربية',
  fMake: 'الماركة',
  fModel: 'الموديل',
  fYear: 'سنة الصنع',
  fMileage: 'الكيلومترات',
  fTransmission: 'ناقل الحركة',
  fFuel: 'الوقود',
  fBodyType: 'نوع الهيكل',
  fCondition: 'الحالة',
  fColor: 'اللون',
  makeHint: 'مثال: تويوتا',
  modelHint: 'مثال: كورولا',
  editCarTitle: 'تعديل إعلان العربية',
  // Cars — my listings
  myCarsTitle: 'عربياتي',
  addNewCar: 'أضف عربية',
  noCarsMineTitle: 'مفيش عربيات',
  noCarsMineDesc: 'ابدأ بإضافة أول عربية ليك',
  // Cars — detail extras
  similarCars: 'عربيات مشابهة',
  reportCar: 'الإبلاغ عن الإعلان',
};

type Strings = typeof ar;

const en: Partial<Strings> = {
  back: 'Back',

  currency: 'EGP',
  perMonth: '/ month',
  priceOnRequest: 'Price on request',
  areaUnit: 'm²',
  in: 'in',

  featured: 'Featured',
  new: 'New',

  tabHome: 'Home',
  tabProperties: 'Properties',
  tabWishlist: 'Saved',
  tabProfile: 'Account',

  heroTitle: 'Find your new home',
  heroTitleLead: 'List your property',
  heroTitleEmphasis: 'commission-free',
  heroTitleAccent: 'Buy & sell with no brokers',
  heroSubtitle: 'Thousands of properties for sale and rent across Egypt',
  trustVerified: 'Verified listings',
  trustDirect: 'Direct contact',
  trustNoCommission: 'No commission',
  searchPillTitle: 'Find your home',
  searchPillHint: 'City, area, or property type',
  searchExamplePrefix: 'Try: ',
  searchExamples: ['Apartment in Maadi', 'Villa in Sheikh Zayed', 'Shop in Nasr City', 'Chalet on the coast', 'Duplex in New Cairo'],
  introTagline: 'Property, no commission',
  sortLabel: 'Sort',
  bannerCta: 'List yours for free',
  bannerEyebrow: 'For property owners',
  roomsShort: 'beds',
  bathsShort: 'baths',
  available: 'Available',
  contactWhatsApp: 'WhatsApp',
  toastWishlistAdded: 'Saved to favorites',
  toastWishlistRemoved: 'Removed from favorites',
  startSearch: 'Start searching',
  exploreByType: 'Explore by type',
  featuredTitle: 'Featured properties',
  latestTitle: 'Latest properties',
  rentSectionTitle: 'For rent',
  saleSectionTitle: 'For sale',
  citySectionTitle: 'Properties in Cairo',
  viewAll: 'View all',
  addListingSub: 'Post in minutes',
  browseProps: 'Browse',
  browsePropsSub: 'Thousands of listings',
  listYourProperty: 'Have a property to list?',
  listYourPropertySub: 'Post it free and reach thousands',

  searchPlaceholder: 'Search by city, area, or property type...',
  resultsCount: (n: number) => `${n} result${n === 1 ? '' : 's'}`,
  searchNoMatches: 'No matches',
  searchAndFilter: 'Search & filter',
  showResults: 'Show results',
  searchHint: 'Search & filter listings',

  filterBtn: 'Filter',
  sortBtn: 'Sort',
  filterTitle: 'Filter results',
  sortTitle: 'Sort',
  apply: 'Apply',
  reset: 'Reset',
  clearAll: 'Clear all',
  all: 'All',
  fListingType: 'Listing type',
  fType: 'Property type',
  fCategory: 'Category',
  fGovernorate: 'Governorate',
  govPickerPlaceholder: 'Select governorate',
  govPickerTitle: 'Select governorate',
  govPickerSearch: 'Search governorate...',
  govPickerEmpty: 'No governorate by that name',
  pricePickerTitle: 'Select price',
  pricePickerPlaceholder: 'Select price',
  areaPickerTitle: 'Select area',
  areaPickerPlaceholder: 'Select area',
  amountPickerCustom: 'Or type a value...',
  amountPickerNone: 'Not specified',
  countPickerPlaceholder: 'Select count',
  yearPickerTitle: 'Select year',
  yearPickerPlaceholder: 'Select year',
  mileagePickerTitle: 'Select mileage',
  mileagePickerPlaceholder: 'Select mileage',
  fPrice: 'Price (EGP)',
  fMinPrice: 'From',
  fMaxPrice: 'To',
  fMinBedrooms: 'Bedrooms (minimum)',
  fMinArea: 'Minimum area (m²)',
  fFinishing: 'Finishing',
  chipMinPrice: (n: string) => `From: ${n}`,
  chipMaxPrice: (n: string) => `To: ${n}`,
  chipMinBedrooms: (n: number) => `Beds: ${n}+`,
  chipMinArea: (n: number) => `Area: ${n}+ m²`,
  loading: 'Loading',
  noResultsTitle: 'No results',
  noResultsDesc: 'Try adjusting your search',
  errorTitle: 'Something went wrong',
  errorDesc: 'Could not load properties, please try again',
  retry: 'Try again',

  contactOwner: 'Contact the owner',
  viewOnMap: 'View on map',
  descriptionLabel: 'Description',
  detailsLabel: 'Details',
  bedrooms: 'Bedrooms',
  bathrooms: 'Bathrooms',
  floor: 'Floor',
  area: 'Area',
  finishingLabel: 'Finishing',
  elevator: 'Elevator',
  garage: 'Garage',
  servicesLabel: 'Available services',
  depositLabel: 'Required deposit',
  listingNumber: 'Listing no.',
  views: 'views',

  signInTitle: 'Sign in',
  signInSubtitle: 'Welcome back to Bt Lee',
  registerTitle: 'Create a new account',
  registerSubtitle: 'Join Bt Lee and start your property journey',
  nameLabel: 'Name',
  emailOrPhoneLabel: 'Email or phone number',
  emailLabel: 'Email',
  phoneLabel: 'Phone number',
  passwordLabel: 'Password',
  signInBtn: 'Sign in',
  createAccountBtn: 'Create account',
  noAccount: "Don't have an account?",
  hasAccount: 'Already have an account?',
  logout: 'Sign out',
  deleteAccount: 'Delete account',
  deleteAccountConfirm:
    'Your account and all your data and listings will be permanently deleted. This cannot be undone. Are you sure you want to continue?',
  deleteAccountCta: 'Delete permanently',
  required: 'This field is required',
  invalidEmail: 'Invalid email address',
  invalidPhone: 'Enter a valid Egyptian phone number (e.g. 01012345678)',
  passwordMin: 'Password must be at least 8 characters',
  loginFailed: 'Invalid login credentials',
  or: 'or',
  googleSignIn: 'Continue with Google',
  googleSignInFailed: 'Google sign-in failed',
  agreePrefix: 'I agree to ',
  termsLink: 'the Terms & Conditions',
  andWord: 'and',
  mustAcceptTerms: 'Please accept the Terms & Conditions first',

  addPropertyTitle: 'Add your listing',
  editPropertyTitle: 'Edit listing',
  fImages: 'Property photos',
  addImages: 'Add photos',
  fBedrooms: 'Bedrooms',
  fBathrooms: 'Bathrooms',
  fFloor: 'Floor',
  fAreaM: 'Area (m²)',
  fPriceOne: 'Price (EGP)',
  fServices: 'Available services',
  fElevator: 'Elevator',
  fGarage: 'Garage',
  fDeposit: 'Required deposit',
  fAreaName: 'Area / neighborhood',
  fDescription: 'Property description',
  fWhatsapp: 'WhatsApp contact number',
  fDuration: 'Listing duration',
  days: 'days',
  optional: '(optional)',
  submitAdd: 'Publish listing',
  submitEdit: 'Save changes',
  uploadingImages: 'Uploading photos...',
  publishing: 'Publishing...',
  addSuccessTitle: 'Your listing was submitted',
  addSuccessDesc: 'It will appear after the team reviews it',
  fillRequired: 'Please complete the required fields',
  imagesRequired: 'Add at least one photo',
  whatsappHint: 'e.g. 01012345678',
  descriptionHint: 'Write the property details (at least 10 characters)',
  phMake: 'e.g. Toyota',
  phModel: 'e.g. Corolla',
  phColor: 'e.g. Black',
  phAreaName: 'e.g. Maadi, Nasr City',
  phFloor: 'e.g. 3',
  phDescription: 'Write clear details that attract interested buyers...',
  fLocation: 'Property location on the map',
  tapToSetLocation: 'Tap the map to set the property location',
  locationSelected: 'Location set',

  myPropertiesTitle: 'My listings',
  addNew: 'Add listing',
  noListingsTitle: 'No listings yet',
  noListingsDesc: 'Start by adding your first listing',
  editListing: 'Edit',
  deleteListing: 'Delete',
  markSold: 'Sold',
  markRented: 'Rented',
  confirmDeleteTitle: 'Delete listing?',
  confirmDeleteDesc: 'This cannot be undone',
  cancel: 'Cancel',
  rejectionReason: 'Rejection reason',
  viewsCount: (n: number) => `${n} views`,

  notificationsTitle: 'Notifications',
  notificationsEmpty: 'No notifications',
  markAllRead: 'Mark all read',

  ratingsTitle: 'Rating',
  ratingsCount: (n: number) => `${n} rating${n === 1 ? '' : 's'}`,
  noRatings: 'No ratings yet',
  rateThis: 'Rate this property',
  rateThisCar: 'Rate this car',
  yourRating: 'Your rating',
  loginToRate: 'Sign in first to rate this property',
  loginToRateCar: 'Sign in first to rate this car',

  reportListing: 'Report listing',
  reportTitle: 'Report this listing',
  reportDetailsPlaceholder: 'Additional details (optional)',
  reportChooseReason: 'Choose a reason',
  reportSubmit: 'Submit report',
  reportSuccess: 'Report submitted, thank you',

  similarProperties: 'Similar properties',
  locationLabel: 'Location',

  ownerProfile: 'Owner profile',
  memberSince: 'Member since',
  listingsCount: (n: number) => `${n} published listing${n === 1 ? '' : 's'}`,
  allListingsByOwner: "All of this owner's listings",
  noOwnerListings: 'No published listings',

  savedSearchesTitle: 'Saved searches',
  savedSearchesEmpty: 'No saved searches',
  savedSearchesEmptyDesc: 'Save a search to get notified about the first new property that matches it',
  saveSearch: 'Save search',
  savedSearchName: 'Search name',
  savedSearchNamePlaceholder: 'e.g. Apartments for rent in Maadi',
  savedSearchNameRequired: 'Enter a name for the search',
  savedSearchSaved: 'Search saved',
  savedSearchDeleteTitle: 'Delete search?',
  applySearch: 'Apply search',

  editProfileTitle: 'Edit profile',
  changePasswordTitle: 'Change password',
  currentPasswordLabel: 'Current password',
  newPasswordLabel: 'New password',
  saveChanges: 'Save changes',
  saveSuccess: 'Changes saved',
  nameInvalid: 'Name must be between 2 and 60 characters',
  passwordLetter: 'Password must contain at least one letter',
  passwordDigit: 'Password must contain at least one number',
  currentPasswordWrong: 'Current password is incorrect',
  passwordChangedTitle: 'Password changed',
  passwordChangedReLogin: 'Sign in again with your new password',

  forgotPassword: 'Forgot password?',
  resetPasswordTitle: 'Reset password',
  resetPasswordDesc: "Enter your email and we'll send you a reset link",
  sendResetLink: 'Send link',
  resetLinkSent: 'Link sent',
  resetLinkSentDesc: "If that email is registered with us, you'll receive a reset link",
  backToLogin: 'Back to sign in',
  newPasswordTitle: 'Set a new password',
  newPasswordSubtitle: 'Choose a strong password for your account',
  confirmPasswordLabel: 'Confirm password',
  setNewPassword: 'Set password',
  passwordNoMatch: 'Passwords do not match',
  resetSuccess: 'Password changed successfully, you can sign in now',
  resetInvalidToken: 'The reset link is invalid or has expired',
  tooManyAttempts: 'Too many attempts. Please wait 15 minutes and try again.',

  onboardingTitle: 'Welcome to Bt Lee',
  onboardingSubtitle: 'What are you looking for?',
  goalBuy: 'Buy a property',
  goalRent: 'Rent a property',
  goalSell: 'Sell or rent out',
  goalBrowse: 'Just browsing',
  skip: 'Skip',
  continue: 'Continue',

  aboutApp: 'About the app',
  privacyTitle: 'Privacy Policy',
  disclaimerTitle: 'Disclaimer',
  dataDeletionTitle: 'Data deletion',

  language: 'Language',
  appearance: 'Appearance',
  light: 'Light',
  dark: 'Dark',
  menuTitle: 'Menu',
  viewProfile: 'View profile',
  contactUs: 'Contact us',

  wishlistEmptyTitle: 'No saved properties',
  wishlistEmptyDesc: 'Save the properties you like and find them here',
  wishlistEmptyTitleCar: 'No saved cars',
  wishlistEmptyDescCar: 'Save the cars you like and find them here',
  profileGuestTitle: 'Welcome to Bt Lee',
  profileGuestDesc: 'Sign in to save properties and post your listing',
  comingSoon: 'Coming soon',
  loginToSave: 'Sign in first to save properties',
  genericError: 'Something went wrong, please try again',

  sectionProperties: 'Properties',
  sectionCars: 'Cars',

  carsHeroLead: 'List your car',
  carsHeroEmphasis: 'commission-free',
  carsHeroSubtitle: 'Thousands of cars for sale and rent across Egypt',
  carsSearchPillTitle: 'Find your car',
  carsSearchExamples: ['Toyota Corolla', 'Hyundai Elantra', 'Kia Sportage', 'Mercedes C180', 'BMW 320i'],
  carsExploreByType: 'Explore by type',
  carsFeaturedTitle: 'Featured cars',
  carsLatestTitle: 'Latest cars',
  carsSaleSectionTitle: 'Cars for sale',
  carsRentSectionTitle: 'Cars for rent',

  carsSearchPlaceholder: 'Search by make or model...',
  carsResultsCount: (n: number) => `${n} car${n === 1 ? '' : 's'}`,
  carsErrorDesc: 'Could not load cars, please try again',
  // Cars — filter sheet
  fMinYear: 'From year',
  fMaxYear: 'To year',
  fMaxMileage: 'Max mileage (km)',

  kmUnit: 'km',
  carYearLabel: 'Year',
  carMileageLabel: 'Mileage',
  carTransmissionLabel: 'Transmission',
  carFuelLabel: 'Fuel',
  carBodyTypeLabel: 'Body type',
  carConditionLabel: 'Condition',
  carColorLabel: 'Color',
  carContactSeller: 'Contact the seller',

  addCarTitle: 'List your car',
  addCarSuccessDesc: 'It will appear after the team reviews it',
  fCarImages: 'Car photos',
  fMake: 'Make',
  fModel: 'Model',
  fYear: 'Year',
  fMileage: 'Mileage (km)',
  fTransmission: 'Transmission',
  fFuel: 'Fuel',
  fBodyType: 'Body type',
  fCondition: 'Condition',
  fColor: 'Color',
  makeHint: 'e.g. Toyota',
  modelHint: 'e.g. Corolla',
  editCarTitle: 'Edit car listing',
  myCarsTitle: 'My cars',
  addNewCar: 'Add a car',
  noCarsMineTitle: 'No cars yet',
  noCarsMineDesc: 'Start by adding your first car',
  similarCars: 'Similar cars',
  reportCar: 'Report listing',
};

/** Locale-aware strings — `S.x` returns the English value when active, else Arabic. */
export const S: Strings = new Proxy(ar, {
  get(target, prop: string) {
    if (getLocale() === 'en') {
      const v = (en as Record<string, unknown>)[prop];
      if (v !== undefined) return v;
    }
    return (target as Record<string, unknown>)[prop];
  },
}) as Strings;
