import { CAR_MAKES, type CarMake } from '@btlee/shared';

const CAR_MAKE_LOGOS: Record<CarMake, number> = {
  Abarth: require('../../../../assets/car-makes/abarth.png'),
  'Alfa Romeo': require('../../../../assets/car-makes/alfa-romeo.png'),
  Audi: require('../../../../assets/car-makes/audi.png'),
  BAIC: require('../../../../assets/car-makes/baic.png'),
  Bentley: require('../../../../assets/car-makes/bentley.png'),
  Bestune: require('../../../../assets/car-makes/bestune.png'),
  BMW: require('../../../../assets/car-makes/bmw.png'),
  Brilliance: require('../../../../assets/car-makes/brilliance.png'),
  BYD: require('../../../../assets/car-makes/byd.png'),
  Cadillac: require('../../../../assets/car-makes/cadillac.png'),
  Changan: require('../../../../assets/car-makes/changan.png'),
  Chery: require('../../../../assets/car-makes/chery.png'),
  Chevrolet: require('../../../../assets/car-makes/chevrolet.png'),
  Citroën: require('../../../../assets/car-makes/citroen.png'),
  Cupra: require('../../../../assets/car-makes/cupra.png'),
  Daewoo: require('../../../../assets/car-makes/daewoo.png'),
  Daihatsu: require('../../../../assets/car-makes/daihatsu.png'),
  DFSK: require('../../../../assets/car-makes/dfsk.png'),
  Dodge: require('../../../../assets/car-makes/dodge.png'),
  Dongfeng: require('../../../../assets/car-makes/dongfeng.png'),
  Exeed: require('../../../../assets/car-makes/exeed.png'),
  Fiat: require('../../../../assets/car-makes/fiat.png'),
  Ford: require('../../../../assets/car-makes/ford.png'),
  Foton: require('../../../../assets/car-makes/foton.png'),
  GAC: require('../../../../assets/car-makes/gac.png'),
  Geely: require('../../../../assets/car-makes/geely.png'),
  'Great Wall': require('../../../../assets/car-makes/great-wall.png'),
  Haval: require('../../../../assets/car-makes/haval.png'),
  Honda: require('../../../../assets/car-makes/honda.png'),
  Hongqi: require('../../../../assets/car-makes/hongqi.png'),
  Hyundai: require('../../../../assets/car-makes/hyundai.png'),
  Infiniti: require('../../../../assets/car-makes/infiniti.png'),
  Isuzu: require('../../../../assets/car-makes/isuzu.png'),
  JAC: require('../../../../assets/car-makes/jac.png'),
  Jaguar: require('../../../../assets/car-makes/jaguar.png'),
  Jeep: require('../../../../assets/car-makes/jeep.png'),
  Jetour: require('../../../../assets/car-makes/jetour.png'),
  Kaiyi: require('../../../../assets/car-makes/kaiyi.png'),
  KGM: require('../../../../assets/car-makes/kgm.png'),
  Kia: require('../../../../assets/car-makes/kia.png'),
  Lada: require('../../../../assets/car-makes/lada.png'),
  'Land Rover': require('../../../../assets/car-makes/land-rover.png'),
  Lexus: require('../../../../assets/car-makes/lexus.png'),
  Mazda: require('../../../../assets/car-makes/mazda.png'),
  'Mercedes-Benz': require('../../../../assets/car-makes/mercedes-benz.png'),
  MG: require('../../../../assets/car-makes/mg.png'),
  MINI: require('../../../../assets/car-makes/mini.png'),
  Mitsubishi: require('../../../../assets/car-makes/mitsubishi.png'),
  Nissan: require('../../../../assets/car-makes/nissan.png'),
  Opel: require('../../../../assets/car-makes/opel.png'),
  Peugeot: require('../../../../assets/car-makes/peugeot.png'),
  Porsche: require('../../../../assets/car-makes/porsche.png'),
  Proton: require('../../../../assets/car-makes/proton.png'),
  Renault: require('../../../../assets/car-makes/renault.png'),
  SEAT: require('../../../../assets/car-makes/seat.png'),
  Skoda: require('../../../../assets/car-makes/skoda.png'),
  Soueast: require('../../../../assets/car-makes/soueast.png'),
  Subaru: require('../../../../assets/car-makes/subaru.png'),
  Suzuki: require('../../../../assets/car-makes/suzuki.png'),
  Tesla: require('../../../../assets/car-makes/tesla.png'),
  Toyota: require('../../../../assets/car-makes/toyota.png'),
  Volkswagen: require('../../../../assets/car-makes/volkswagen.png'),
  Volvo: require('../../../../assets/car-makes/volvo.png'),
  Zeekr: require('../../../../assets/car-makes/zeekr.png'),
};

export function getCarMakeLogo(make: string): number | null {
  const canonical = CAR_MAKES.find(
    (item) => item.toLocaleLowerCase() === make.toLocaleLowerCase()
  );
  return canonical ? CAR_MAKE_LOGOS[canonical] : null;
}
